Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2023-12, with the labels that each got.

#289 [PASELC-624] Stand-in IBAN box activation
  .github/workflows/release_deploy.yml
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
Labels: bug, size/small

#290 fix: resolved wrong generation of request body in IBAN updates
  package.json
  src/model/Iban.tsx
  src/pages/iban/IbanPage.tsx
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/pages/iban/addEditIban/AddEditIbanPage.tsx
  src/pages/iban/detail/IbanDetailPage.tsx
Labels: bug

#292 fix delegation
  src/api/BackofficeClient.ts
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/services/channelService.ts
  src/utils/constants.ts
Labels: size/small

#294 [PASELC-590] fix delegation for Stations
  src/api/BackofficeClient.ts
  src/api/__tests__/PortalApiClient.test.ts
  src/components/Header.tsx
  src/components/SideMenu/SideMenu.tsx
  src/hooks/useSelectedParty.tsx
  src/hooks/useSigninData.tsx
  src/locale/it.json
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/iban/list/IbanTable.tsx
  src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/detail/components/StationDetailsValidation.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/services/__mocks__/channelService.ts
  src/services/__tests__/channelService.test.ts
  src/services/channelService.ts
Labels: bug, size/small

#291 feat: added dynamic version info generation on app build
  .gitignore
  package.json
  version.sh
Labels: enhancement, size/small

#295 Paselc 642 uat fe configurazione stazione label status errata
  .github/workflows/release_deploy.yml
  src/api/BackofficeClient.ts
  src/pages/stations/detail/StationDetailPage.tsx
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/stationService.ts
  src/services/channelService.ts
  src/services/stationService.ts
  src/utils/constants.ts
Labels: bug, size/small

#296 Paselc 646 associa ec con il campo sbagliato
  src/pages/stations/stationAssociateEC/ECAccountItemSelection.tsx
  src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/services/__mocks__/channelService.ts
Labels: size/large

#297 [PASELC-647] fix: added error catch during PT data retrieve
  src/hooks/useSigninData.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
Labels: bug, size/small

#299 release and deploy GHA
  .github/workflows/release_deploy.yml
  src/pages/stations/detail/components/StationDetails.tsx
  src/utils/constants.ts
Labels: size/large

#302 [PASELC-656] Button for exporting IBANs as CSV
  .github/workflows/integration_test.yml
  integration-test/00_login.js
  integration-test/00_login_ec.js
  integration-test/01_iban_add.js
  integration-test/02_create_station.js
  integration-test/03_export_ibans.js
  integration-test/package.json
  integration-test/run_integration.sh
  integration-test/yarn.lock
  package.json
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/RolePermission.ts
  src/pages/dashboard/DashboardPage.tsx
  src/pages/dashboard/components/DownloadSection.tsx
  src/services/__mocks__/ibanService.ts
  src/services/ibanService.ts
  src/utils/common-utils.ts
Labels: enhancement, size/large

#301 [PASELC-641] Various fixes on IBAN, Station and Channel sections
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/utils/common-utils.ts
Labels: bug, size/small
