Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2023-11, with the labels that each got.

#232 PASELC-541 add fetch to get all delegated psp to channel association
  sonar-project.properties
  src/api/PortalApiClient.ts
  src/api/__tests__/PortalApiClient.test.ts
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/channels/channelAssociatePSP/PSPAccountItemSelection.tsx
  src/pages/channels/channelAssociatePSP/PSPSelectionSearch.tsx
  src/pages/channels/channelAssociatePSP/PSPSelectionSearchItemContainer.tsx
  src/pages/channels/channelAssociatePSP/__tests__/ChannelAssociatePSPPage.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx
  src/services/__mocks__/channelService.ts
  src/services/__tests__/channelService.test.ts
  src/services/channelService.ts
Labels: size/large

#264 Enable dashboards, channels, stations and operation-table in prod
  .github/workflows/release_deploy.yml
Labels: size/small

#265 Fix useSignInData custom hook
  src/hooks/useSigninData.tsx
Labels: size/small

#268 Fix Channel details
  src/pages/channels/detail/components/ChannelDetailsWrap.tsx
Labels: size/small

#269 PASELC-592 PASELC-591 + fix delegation param
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/detail/components/ChannelDetailsWrap.tsx
  src/pages/dashboard/components/ECRegistrationData.tsx
  src/pages/stations/__tests__/StationDetailPage.test.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/services/__mocks__/nodeService.ts
  src/services/nodeService.ts
Labels: size/small

#270 PASELC-593 fix psp selection search single item clickability
  src/pages/channels/channelAssociatePSP/PSPSelectionSearch.tsx
Labels: size/small

#275 [PASELC-596] fix: resolved wrong BIC format
  README.md
  package.json
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
Labels: bug

#276 [PASELC-610] feat: enabled IBANs functionality
  .github/workflows/release_deploy.yml
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
Labels: size/small

#277 [PASELC-595] fix: updated total items info
  openApi/portal-api-docs.json
  package.json
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/stationService.ts
Labels: bug, size/small

#279 [PASELC-623] fix: resolved optional fields
  openApi/portal-api-docs.json
  package.json
  src/model/Party.tsx
  src/model/PartyDetail.tsx
Labels: bug, size/small

#272 [PASELC-508] feat: added modal for intermediation confirm
  src/locale/it.json
  src/pages/components/ConfirmModal.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInECForm.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPage.test.tsx
  src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
Labels: enhancement, size/large

#281 [PASELC-622] Error with CI/PSP already registered
  openApi/portal-api-docs.json
Labels: bug, size/small
