Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-01, with the labels that each got.

#308 [PASELC-673] fix: Station-EC association
  .env.development.local
  integration-test/00_login.js
  integration-test/03_export_ibans.js
  integration-test/04_associate_station.js
  integration-test/run_integration.sh
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/utils/constants.ts
Labels: size/large

#311 [PASELC-675] fix: add 'itself' as associable institution for stations and channels
  package.json
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/services/nodeService.ts
Labels: bug, size/small

#312 Iban test
  package.json
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/addEditIban/AddEditIbanPage.tsx
  src/pages/iban/detail/IbanDetailPage.tsx
  src/pages/iban/list/IbanTableColumns.tsx
  src/services/__mocks__/ibanService.ts
  src/utils/common-utils.ts
Labels: size/small

#313 [PASELC-648] Resolved error on creation of channel/station for PT brokers
  src/api/BackofficeClient.ts
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/services/__mocks__/stationService.ts
  src/services/stationService.ts
Labels: bug, size/small

#307 [PASELC-653] fix: add formatting for station-EC association codes
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/utils/common-utils.ts
Labels: bug

#310 [PASELC-652] feat: added CI fiscal code in CI associated to station
  package.json
  src/locale/it.json
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/utils/common-utils.ts
Labels: enhancement, size/small

#314 feat: major bug-fixing and enhancements
  .github/workflows/release_deploy.yml
  package.json
  src/api/BackofficeClient.ts
  src/model/Station.tsx
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
  src/pages/channels/channelPSPList/ChannelPSPListPage.tsx
  src/pages/channels/channelPSPList/ChannelPSPTable.tsx
  src/pages/channels/channelPSPList/ChannelPSPTableEmpty.tsx
  src/pages/channels/channelPSPList/ChannelPSPTableSearchBar.tsx
  src/pages/channels/channelPSPList/QuickFilterCustom.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/stationECList/QuickFilterCustom.tsx
  src/pages/stations/stationECList/StationECPage.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/stations/stationECList/StationECTableEmpty.tsx
  src/pages/stations/stationECList/StationECTableSearchBar.tsx
  src/services/channelService.ts
  src/services/stationService.ts
Labels: enhancement, size/large

#316 [PASELC-684] fix: resolved bug on station check
  src/api/BackofficeClient.ts
  src/model/Station.tsx
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/services/stationService.ts
  src/utils/station-utils.ts
Labels: bug, size/small

#315 [PASELC-643] apikey FdR
  .env
  .env.development.local
  .env.test.local
  .github/workflows/release_deploy.yml
  package.json
  src/model/ApiKey.tsx
  src/pages/apiKeys/AddApiKeyPage.tsx
  src/services/partyService.ts
  src/services/productService.ts
  src/utils/constants.ts
  src/utils/env.ts
Labels: size/large

#319 [PASELC-660] fix: removed '-' char for channels' undefined dates
  package.json
  src/pages/channels/list/ChannelsTableColumns.tsx
Labels: bug, size/small

#318 [PASELC-688] apikey
  src/locale/it.json
  src/model/ApiKey.tsx
  src/pages/apiKeys/AddApiKeyPage.tsx
  src/pages/apiKeys/ApiKeysCard.tsx
  src/pages/apiKeys/ApiKeysPage.tsx
  src/services/apiKeyService.ts
  src/utils/constants.ts
Labels: size/large

#322 [PASELC-681] fix: refactored `extractResponse method` for correctly handle errors
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/utils/client-utils.ts
Labels: bug, size/small

#321 [PASELC-693] fix iban regex
  src/pages/iban/IbanPage.tsx
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/utils/common-utils.ts
  src/utils/constants.ts
Labels: size/large

#323 [PASELC-691] Download label
  package.json
  src/api/BackofficeClient.ts
  src/model/RolePermission.ts
  src/pages/dashboard/components/DownloadSection.tsx
  src/services/ibanService.ts
Labels: size/small

#327 feat: Dynamic export status
  package.json
  src/api/BackofficeClient.ts
  src/pages/dashboard/components/DownloadSection.tsx
  src/services/__mocks__/ibanService.ts
  src/services/ibanService.ts
Labels: enhancement

#326 [PASELC-694] feat: activated creditor institution's export button
  src/api/BackofficeClient.ts
  src/pages/dashboard/components/DownloadSection.tsx
  src/services/__mocks__/ibanService.ts
  src/services/ibanService.ts
Labels: enhancement, size/small

#328 [PASELC-663][PASELC-659] fix: resolved some bugs on frontend found after Go-Live event
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/detail/components/ChannelDetailsWrap.tsx
  src/pages/stations/list/StationsTableColumns.tsx
Labels: bug, size/small

#329 [PASELC-716] chore: Updates before minor release
  src/model/RolePermission.ts
  src/pages/dashboard/components/DownloadSection.tsx
Labels: bug, size/small

#331 [PASELC-720] fix: added more eloquent error messages
  package.json
  src/locale/it.json
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
Labels: bug, size/small

#332 [PASELC-701] feat: added CBIll interbank code for CIs
  package.json
  src/pages/dashboard/components/ECRegistrationData.tsx
Labels: enhancement, size/small

#333 [PASELC-613] Check last valid Iban
  .env.development.local
  .github/workflows/integration_test.yml
  integration-test/00_login.js
  integration-test/01_iban_add.js
  integration-test/01_iban_delete.js
  integration-test/02_create_station.js
  integration-test/03_export_ibans.js
  integration-test/04_associate_station.js
  integration-test/run_integration.sh
  src/api/BackofficeClient.ts
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/pages/iban/detail/IbanDetailPage.tsx
  src/utils/constants.ts
Labels: size/large

#334 hotfix: Excluded FdR APIM's API keys
  src/model/ApiKey.tsx
Labels: bug, size/small

#338 [PASELC-696] feat: updated query param for CI-by-station search
  src/api/BackofficeClient.ts
  src/pages/stations/stationECList/StationECPage.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/stations/stationECList/StationECTableSearchBar.tsx
Labels: enhancement, size/small

#339 fix: resolved error with ProblemJson object
  .github/workflows/release_deploy.yml
  package.json
  src/api/BackofficeClient.ts
  src/services/stationService.ts
Labels: bug, size/small

#340 fix: changed wrong label name on EC-by-station search
  src/locale/it.json
Labels: bug, size/small

#341 fix: added tax code search on available CIs for station
  src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
  src/utils/env.ts
Labels: enhancement, size/small

#342 [PASELC-735] feat: added station version field in station detail
  package.json
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/pages/stations/detail/components/StationDetails.tsx
  src/pages/stations/detail/components/StationDetailsValidation.tsx
Labels: bug, size/small
