Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-03, with the labels that each got.

#378 [VAS-737] feat: Implemented Commission Bundle Detail's page
  .env.development.local
  .env.test.local
  .github/workflows/release_deploy.yml
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/PaddedDrawer.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx.old
  src/locale/it.json
  src/model/CommissionBundle.ts
  src/model/RolePermission.ts
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/__tests__/CommissionBundlesPage.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundlePage.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailConfiguration.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailTaxonomies.test.tsx
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesEmpty.test.tsx
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesSearchBar.test.tsx
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesTable.test.tsx
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesTableColumns.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/list/CommissionBundlesEmpty.tsx
  src/pages/commisionalBundles/list/CommissionBundlesSearchBar.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalPackages/CommissionPackagesPage.tsx
  src/pages/commisionalPackages/__tests__/CommissionPackagesPage.test.tsx
  src/pages/commisionalPackages/__tests__/addEditCommissionPackage/AddEditCommissionPackagePage.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesEmpty.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesTable.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesTableColumns.test.tsx
  src/pages/commisionalPackages/addEditCommissionPackage/AddEditCommissionPackagePage.tsx
  src/routes.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/institutionsService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
  src/utils/common-utils.ts
  src/utils/constants.ts
  src/utils/env.ts
Labels: enhancement, size/large

#382 [VAS-770] Fixed iban title tag
  src/locale/it.json
Labels: bug, size/small

#381 [VAS-802] Added Maintenance page
  .github/workflows/release_deploy.yml
  src/App.tsx
  src/locale/it.json
  src/pages/maintenance/MaintenancePage.tsx
Labels: enhancement, size/small

#383 chore: add mantainance flag on prod
  .github/workflows/release_deploy.yml
Labels: size/small

#384 [VAS-508] feat: Add productId query param on assistence redirect
  src/components/CommonHeader/CommonHeader.tsx
Labels: size/small

#387 [VAS-837] fix: Backoffice client API
  src/api/BackofficeClient.ts
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundlePage.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailTaxonomies.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/taxonomyService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
  src/services/taxonomyService.ts
Labels: size/large

#388 feature flags
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/Layout/Layout.tsx
  src/components/SideMenu/SideMenu.tsx
  src/decorators/withFeatureFlags.tsx
  src/decorators/withParties.tsx
  src/hooks/useFeatureFlags.ts
  src/pages/channels/list/__tests__/ChannelsTableSearchBar.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/components/__tests__/commonFunctions.test.ts
  src/pages/components/__tests__/isOperator.test.ts
  src/pages/components/commonFunctions.ts
  src/pages/dashboard/__tests__/NextSteps.test.tsx
  src/pages/stations/__tests__/StationDetails.test.tsx
  src/redux/slices/featureFlagsSlice.ts
  src/redux/store.ts
  src/services/featureFlagService.ts
  src/utils/constants.ts
Labels: size/large

#392 feature flag maintenance
  .env.development.local
  .github/workflows/release_deploy.yml
  CODEOWNERS
  src/App.tsx
  src/components/Layout/Layout.tsx
Labels: size/small

#390 [VAS-768] feat: Create api key bo external
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/ApiKey.tsx
  src/pages/apiKeys/ApiKeysCard.tsx
  src/services/__mocks__/apiKeyService.ts
  src/services/__tests__/apiKeyService.test.ts
  src/services/apiKeyService.ts
Labels: size/small

#379 [VAS-720] Rework Taxonomies
  .eslintrc.js
  package.json
  public/file/taxonomiesExample.csv
  src/components/PaddedDrawer.tsx
  src/locale/it.json
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundlePage.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleTaxonomies.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/BundleTaxonomiesCheckboxButton.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/BundleTaxonomiesDrawer.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/BundleTaxonomiesGroupButton.test.tsx
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/BundleTaxonomiesTable.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailConfiguration.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailTaxonomies.test.tsx
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesTableColumns.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/BundleTaxonomiesTable.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesCheckboxButton.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesGroupButton.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/redux/slices/bundleDetailsSlice.ts
  src/redux/store.ts
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/taxonomyService.ts
  src/services/__tests__/taxonomyService.test.ts
  src/services/taxonomyService.ts
  yarn.lock
Labels: enhancement, size/large

#391 fixed AddEditChannelForm.tsx for operator configs
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
Labels: bug, size/small

#395 fix: generated types
  openApi/scripts/api-portal_fixPostGen.js
Labels: size/small

#396 [VAS-803] Introduced bundle state chip
  src/locale/it.json
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesTableColumns.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/utils/common-utils.ts
Labels: enhancement, size/small

#397 [VAS-855] feat: Add column due date in iban table
  src/locale/it.json
  src/pages/iban/list/IbanTableColumns.tsx
Labels: enhancement, size/small

#398 [VAS-845] feat: Remove accession date from ec dashboard page
  src/pages/dashboard/components/ECRegistrationData.tsx
Labels: size/small

#399 [VAS-860] fix: wrong psp code on node signin
  src/hooks/useSigninData.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  yarn.lock
Labels: bug, size/small

#400 [VAS-809] feat: introduced filter for payment types
  src/services/configurationService.ts
  src/utils/constants.ts
Labels: enhancement, size/small

#401 [VAS-777] feat: Bundle Table for Creditor Institutions
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/PaddedDrawer.tsx
  src/hooks/usePermissions.ts
  src/locale/it.json
  src/model/RolePermission.ts
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/__tests__/detail/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/__tests__/list/CommissionBundlesTableColumns.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/list/CommissionBundlesSearchBar.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
Labels: enhancement, size/large

#404 fix: payment types filter
  src/services/configurationService.ts
  src/utils/constants.ts
Labels: bug, size/small

#402 [VAS-510] fix: StandIn CUP iban edit form
  .gitignore
  package.json
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx.old
  src/services/__mocks__/ibanService.ts
  src/services/ibanService.ts
Labels: bug, size/large

#405 [VAS-868] fix psp creation
  src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx
  src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx.old
  src/pages/dashboard/components/PSPRegistrationData.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
Labels: size/large

#407 [VAS-790] fix: Improve EC search filter
  src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
Labels: size/small

#409 [VAS-309] feat: Defined iban validation algorithm
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
  src/utils/common-utils.ts
Labels: enhancement, size/large

#410 [VAS-872] fix: Stand in and cup selection
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
Labels: bug, size/small

#408 fix: Broker list error handling
  src/App.tsx
  src/components/SideMenu/SideMenu.tsx
  src/hooks/usePermissions.ts
  src/locale/it.json
  src/model/RolePermission.ts
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/services/__mocks__/institutionsService.ts
Labels: bug, size/small

#413 fix: StandIn and CUP iban selection edge case
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
Labels: bug, size/small

#412 fix: Create iban response handling
  .github/workflows/code_review.yml
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
  src/utils/client-utils.ts
  src/utils/common-utils.ts
Labels: size/small

#415 fix: Fixed getChannels from broker tax code
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/institutionsService.ts
Labels: bug, size/small

#411 hotfix: cf was undefined
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/utils/constants.ts
Labels: bug, size/large

#417 [VAS-555] feat: Creditor institution broker delegation page
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/SideMenu/SideMenu.tsx
  src/locale/it.json
  src/model/RolePermission.ts
  src/pages/delegations/DelegationsPage.tsx
  src/pages/delegations/__tests__/DelegationsPage.test.tsx
  src/pages/delegations/__tests__/list/DelegationsTable.test.tsx
  src/pages/delegations/__tests__/list/DelegationsTableColumns.test.tsx
  src/pages/delegations/__tests__/list/DelegationsTableEmpty.test.tsx
  src/pages/delegations/__tests__/list/DelegationsTableSearchBar.test.tsx
  src/pages/delegations/list/DelegationsTable.tsx
  src/pages/delegations/list/DelegationsTableColumns.tsx
  src/pages/delegations/list/DelegationsTableEmpty.tsx
  src/pages/delegations/list/DelegationsTableSearchBar.tsx
  src/routes.tsx
  src/services/__mocks__/brokerService.ts
  src/services/brokerService.ts
  src/utils/constants.ts
Labels: enhancement, size/large

#418 fix to handle when the abi_code is N/A
  .env.development.local
  src/bootstrap.tsx
  src/decorators/withSelectedParty.tsx
  src/hooks/useParties.tsx
  src/hooks/useSelectedParty.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/services/__mocks__/partyService.ts
Labels: bug
