Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-10, with the labels that each got.

#686 fix: Create station payment options fields
  src/api/BackofficeClient.ts
  src/pages/stations/addEditStation/AddEditStationForm.tsx
Labels: size/small, patch

#687 [PPANTT-138] feat: Add flagStandIn to Channel & Station models
  package.json
  src/api/BackofficeClient.ts
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/services/__mocks__/stationService.ts
Labels: size/small, minor

#689 fix: Implement feature flags for Station's REST endpoint & ODP sections
  package.json
  src/components/WrapperCommon/GetAlert.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/pages/stations/detail/components/__tests__/StationDetails.test.tsx
  src/utils/station-utils.ts
Labels: patch

#695 [PPANTT-151] feat: Updated taxonomy extraction
  package.json
  src/components/WrapperCommon/GetAlert.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/pages/stations/detail/components/__tests__/StationDetails.test.tsx
  src/utils/bundle-utils.ts
  src/utils/station-utils.ts
Labels: minor

#696 Ppantt 151 feat update taxonomy extraction
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/utils/bundle-utils.ts
Labels: size/small, minor

#698 [PPANTT-156] fix: Channel forwarder url & Station dev forwarder url
  src/model/Channel.tsx
  src/model/Station.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
Labels: size/small, patch

#701 [PPANTT-55] feat: Rework getInstitutions
  .github/workflows/ci_code_review.yml
  package.json
  src/api/BackofficeClient.ts
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/Header.tsx
  src/hooks/useParties.tsx
  src/hooks/useSelectedParty.tsx
  src/model/Party.tsx
  src/redux/slices/partiesSlice.ts
  src/services/__mocks__/institutionsService.ts
  src/services/__mocks__/partyService.ts
  src/services/__tests__/institutionService.test.ts
  src/services/__tests__/partyService.test.ts
  src/services/institutionService.ts
  src/services/partyService.ts
Labels: size/large, minor

#708 [PPANTT-161] fix: Station Maintenances' hours daytime saving format
  package.json
  src/pages/stationMaintenances/addEditDetail/StationMaintenanceAddEditDetail.tsx
  src/utils/common-utils.ts
  yarn.lock
Labels: size/large, patch

#707 [PPANTT-158] fix: Fix Station maintenance flag standIn
  src/pages/stationMaintenances/addEditDetail/StationMaintenanceAddEditDetail.tsx
  src/pages/stationMaintenances/addEditDetail/__tests__/StationMaintenanceAddEditDetail.test.tsx
  src/services/__mocks__/stationMaintenancesService.ts
Labels: size/small, patch

#700 Next release 1.37
  .github/workflows/ci_code_review.yml
  package.json
  src/api/BackofficeClient.ts
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/CommonHeader/__tests__/CommonHeader.test.tsx
  src/components/CommonHeader/__tests__/MyHeaderProduct.test.tsx
  src/components/Header.tsx
  src/hooks/useParties.tsx
  src/hooks/useSelectedParty.tsx
  src/model/Party.tsx
  src/redux/slices/partiesSlice.ts
  src/services/__mocks__/institutionsService.ts
  src/services/__mocks__/partyService.ts
  src/services/__tests__/institutionService.test.ts
  src/services/__tests__/partyService.test.ts
  src/services/institutionService.ts
  src/services/partyService.ts
Labels: size/large, minor

#714 [PPANTT-173] fix: check on logo
  src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
Labels: size/small, patch

#715 fix: Station Maintenances pagination
  src/pages/stationMaintenances/list/StationMaintenancesTable.tsx
Labels: size/small, patch

#721 [PPANTT-175] fix: PT api key list
  src/model/ApiKey.tsx
  src/model/__tests__/ApiKey.test.tsx
  src/pages/apiKeys/AddApiKeyPage.tsx
Labels: size/small, patch
