Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-02, with the labels that each got.

#344 [PASELC-745] Fix Station Creation
  .github/workflows/release_deploy.yml
  src/hooks/useLogin.ts
  src/pages/components/commonFunctions.ts
  src/pages/iban/detail/IbanDetailPage.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/utils/constants.ts
  src/utils/station-utils.ts
Labels: size/small

#346 [VAS-679] fix: Protected all routes that needed privileges
  src/App.tsx
  src/components/SideMenu/SideMenu.tsx
  src/model/RolePermission.ts
Labels: bug

#345 [VAS-540] feat: Implement getBundlesByPSP
  src/api/BackofficeClient.ts
  src/components/SideMenu/SideMenu.tsx
  src/locale/it.json
  src/pages/commisionalPackages/CommissionPackagesPage.tsx
  src/pages/commisionalPackages/list/CommissionPackagesTable.tsx
  src/pages/commisionalPackages/list/CommissionPackagesTableColumns.tsx
  src/services/__mocks__/commissionPackageService.ts
  src/services/bundleService.ts
Labels: enhancement

#355 Jest test
  .env.test.local
  .github/workflows/code_review.yml
  src/__tests__/App.test.tsx
  src/__tests__/App.test.tsx.old
  src/api/__mocks__/BackofficeClient.ts
  src/api/__tests__/PortalApiClient.test.ts.old
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx.old
  src/decorators/__tests__/withLogin.test.tsx
  src/decorators/__tests__/withLogin.test.tsx.old
  src/decorators/__tests__/withSelectedParty.test.tsx
  src/decorators/__tests__/withSelectedParty.test.tsx.old
  src/decorators/__tests__/withSelectedPartyProducts.test.tsx
  src/decorators/__tests__/withSelectedPartyProducts.test.tsx.old
  src/model/__tests__/Party.test.ts.old
  src/model/__tests__/Product.test.ts
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx.old
  src/pages/channels/channelAssociatePSP/__tests__/ChannelAssociatePSPPage.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/ChannelAssociatePSPPage.test.tsx.old
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx.old
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableEmpty.test.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableEmpty.test.tsx.old
  src/pages/channels/detail/__tests__/ChannelDetails.test.tsx
  src/pages/channels/detail/__tests__/ChannelDetails.test.tsx.old
  src/pages/commisionalPackages/__tests__/CommissionPackagesTableColumns.test.tsx
  src/pages/commisionalPackages/__tests__/CommissionPackagesTableColumns.test.tsx.old
  src/pages/dashboard/__tests__/DashboardPage.test.tsx
  src/pages/dashboard/__tests__/DashboardPage.test.tsx.old
  src/pages/dashboard/__tests__/ECRegistrationData.test.tsx
  src/pages/dashboard/__tests__/ECRegistrationData.test.tsx.old
  src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx
  src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx.old
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx.old
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx.old
  src/pages/iban/list/__tests__/IbanTable.test.tsx
  src/pages/iban/list/__tests__/IbanTable.test.tsx.old
  src/pages/operationTable/addEditOperationTable/__tests__/AddEditOperationTablePage.test.tsx
  src/pages/operationTable/addEditOperationTable/__tests__/AddEditOperationTablePage.test.tsx.old
  src/pages/stations/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/__tests__/AddEditStationForm.test.tsx.old
  src/pages/stations/stationAssociateEC/__tests__/ECSelectionSearch.test.tsx
  src/pages/stations/stationAssociateEC/__tests__/ECSelectionSearch.test.tsx.old
  src/pages/stations/stationECList/__tests__/StationECTableEmpty.test.tsx
  src/pages/stations/stationECList/__tests__/StationECTableEmpty.test.tsx.old
  src/services/__tests__/partyService.test.ts
  src/services/__tests__/partyService.test.ts.old
  src/services/__tests__/productService.test.ts
  src/services/__tests__/productService.test.ts.old
  src/services/__tests__/stationService.test.ts.old
  src/utils/__tests__/station-utils.test.ts
  src/utils/__tests__/station-utils.test.ts.old
Labels: size/large

#356 [VAS-709] fix: Updated delegates api to be retrieved for a filtered s…
  openApi/scripts/api-portal_fixPostGen.js
  src/api/BackofficeClient.ts
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/services/channelService.ts
  src/utils/constants.ts
Labels: bug, enhancement, size/small

#358 [VAS-721] fix: Validity date check on iban create
  src/pages/iban/IbanPage.tsx
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
Labels: bug, size/small

#357 [VAS-711] fix: Add alert for empty next step
  src/locale/it.json
  src/pages/dashboard/components/NextSteps.tsx
Labels: bug, size/small

#354 [VAS-541] feat: Implement the APIs needed in the create bundle page
  package.json
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/CommissionPackage.ts
  src/model/PaymentType.tsx
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/channels/channelPSPList/ChannelPSPTable.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/channels/list/ChannelsTable.tsx
  src/pages/commisionalPackages/__tests__/AddEditCommissionPackageForm.test.tsx
  src/pages/commisionalPackages/__tests__/AddEditCommissionPackageForm.test.tsx.old
  src/pages/commisionalPackages/__tests__/AddEditCommissionPackagePage.test.tsx
  src/pages/commisionalPackages/__tests__/AddEditCommissionPackagePage.test.tsx.old
  src/pages/commisionalPackages/__tests__/CommissionPackagesSearchBar.test.tsx.old
  src/pages/commisionalPackages/__tests__/CommissionPackagesTable.test.tsx.old
  src/pages/commisionalPackages/addEditCommissionPackage/AddEditCommissionPackagePage.tsx
  src/pages/commisionalPackages/addEditCommissionPackage/components/AddEditCommissionPackageForm.tsx
  src/pages/commisionalPackages/list/CommissionPackagesTable.tsx
  src/pages/stations/list/StationsTable.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/commissionPackageService.ts
  src/services/__mocks__/configurationService.ts
  src/services/__mocks__/institutionsService.ts
  src/services/__mocks__/taxonomyService.ts
  src/services/__tests__/channelService.test.ts
  src/services/bundleService.ts
  src/services/channelService.ts
  src/services/commissionPackageService.ts
  src/services/configurationService.ts
  src/services/institutionService.ts
  src/services/taxonomyService.ts
  src/utils/constants.ts
  yarn.lock
Labels: enhancement, size/large

#360 [VAS-736] Implemented dynamic package item table action menu
  src/pages/commisionalPackages/list/CommissionPackagesTableColumns.tsx
Labels: enhancement, size/small

#361 [VAS-735] Change default timeout for type A primitive
  src/pages/stations/__tests__/StationDetails.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/services/__mocks__/stationService.ts
Labels: size/small

#365 [VAS-744] fix: Operation table box permissions
  integration-test/05_operationTable_addEdit.js
  integration-test/run_integration.sh
  package.json
  src/App.tsx
  src/model/RolePermission.ts
  src/pages/dashboard/DashboardPage.tsx
Labels: size/small

#368 [VAS-694] feat: Updated PUT PSP API to use tax code
  src/api/BackofficeClient.ts
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/services/__mocks__/nodeService.ts
  src/services/__tests__/institutionService.test.ts
  src/services/__tests__/nodeService.test.ts
  src/services/nodeService.ts
Labels: size/small

#370 fix
  package.json
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
Labels: size/small

#366 [VAS-742] chore: Fixed and decommented unit tests
  src/pages/apiKeys/__tests__/AddApiKeyPage.test.tsx
  src/pages/apiKeys/__tests__/ApiKeysCard.test.tsx
  src/pages/apiKeys/__tests__/ApiKeysPage.test.tsx
  src/pages/auth/__tests__/Auth.test.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelFormSectionTitle.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/ChannelAssociatePSPPage.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/ChannelAssociatePSPPage.test.tsx.old
  src/pages/channels/channelAssociatePSP/__tests__/PSPAccountItemSelection.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx.old
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearchInput.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearchItemContainer.test.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPListPage.test.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTable.test.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableColumns.test.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableEmpty.test.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableEmpty.test.tsx.old
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableSearchBar.test.tsx
  src/pages/channels/detail/__tests__/ChannelDetailPage.test.tsx
  src/pages/channels/detail/__tests__/ChannelDetails.test.tsx
  src/pages/channels/detail/__tests__/ChannelDetails.test.tsx.old
  src/pages/channels/detail/__tests__/ChannelDetailsWrap.test.tsx
  src/pages/channels/detail/__tests__/DetailButton.test.tsx
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/list/__tests__/ChannelsPage.test.tsx
  src/pages/channels/list/__tests__/ChannelsTableEmpty.test.tsx
  src/pages/channels/list/__tests__/ChannelsTableSearchBar.test.tsx
  src/pages/commisionalPackages/__tests__/AddEditCommissionPackageForm.test.tsx.old
  src/pages/commisionalPackages/__tests__/AddEditCommissionPackagePage.test.tsx.old
  src/pages/commisionalPackages/__tests__/CommissionPackagesPage.test.tsx
  src/pages/commisionalPackages/__tests__/CommissionPackagesTableColumns.test.tsx.old
  src/pages/commisionalPackages/__tests__/addEditCommissionPackage/AddEditCommissionPackageForm.test.tsx
  src/pages/commisionalPackages/__tests__/addEditCommissionPackage/AddEditCommissionPackagePage.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesEmpty.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesSearchBar.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesTable.test.tsx
  src/pages/commisionalPackages/__tests__/list/CommissionPackagesTableColumns.test.tsx
  src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
Labels: size/large

#376 [VAS-695] Changed getFirstValidChannelCode API path param
  src/api/BackofficeClient.ts
  src/pages/channels/addEditChannel/AddEditChannelPage.tsx
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/nodeService.ts
  src/services/channelService.ts
  src/services/nodeService.ts
Labels: enhancement, size/small

#377 [VAS-696] Update disassociatePSPFromChannel API to use PSP tax code
  src/api/BackofficeClient.ts
  src/pages/channels/channelAssociatePSP/__tests__/ChannelAssociatePSPPage.test.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx
  src/pages/channels/channelPSPList/ChannelPSPTable.tsx
  src/pages/channels/channelPSPList/ChannelPSPTableColumns.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTable.test.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/institutionsService.ts
  src/services/__tests__/channelService.test.ts
  src/services/__tests__/institutionService.test.ts
  src/services/channelService.ts
Labels: size/large
