Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-08, with the labels that each got.

#628 [PPANTT-42] feat: Station maintenances create/edit/details page
  package.json
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/Layout/SuccessAlertLayout.tsx
  src/components/Layout/__tests__/SuccessAlertLayout.test.tsx
  src/locale/it.json
  src/model/StationMaintenance.ts
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/stationMaintenances/addEditDetail/StationMaintenanceAddEditDetail.tsx
  src/pages/stationMaintenances/addEditDetail/__tests__/StationMaintenanceAddEditDetail.test.tsx
  src/pages/stationMaintenances/list/StationMaintenancesHoursSummary.tsx
  src/pages/stationMaintenances/list/StationMaintenancesPage.tsx
  src/pages/stationMaintenances/list/StationMaintenancesTable.tsx
  src/pages/stationMaintenances/list/StationMaintenancesTableColumns.tsx
  src/pages/stationMaintenances/list/__tests__/StationMaintenancesHoursSummary.test.tsx
  src/pages/tosAndPrivacy/TosAndPrivacy.tsx
  src/pages/tosAndPrivacy/__tests__/TosAndPrivacy.test.tsx
  src/pages/tos_and_privacy/__tests__/TOS_AND_PRIVACY.test.tsx
  src/redux/hooks.ts
  src/redux/slices/stationMaintenancesSlice.ts
  src/redux/store.ts
  src/routes.tsx
  src/services/__mocks__/stationMaintenancesService.ts
  src/services/__tests__/stationMaintenancesService.test.ts
  src/services/stationMaintenancesService.ts
  src/utils/common-utils.ts
  src/utils/constants.ts
Labels: size/large, minor

#634 hotfix: Node sign in on new registration
  src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
Labels: size/large, patch, hotfix

#635 Merge main next 1.29.3
  package.json
  src/App.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
  src/pages/tos_and_privacy/TOS_AND_PRIVACY.tsx
  src/pages/tos_and_privacy/__tests__/TOS_AND_PRIVACY.test.tsx
Labels: size/large

#621 Next
  package.json
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/Form/ECSelection.tsx
  src/components/Layout/SuccessAlertLayout.tsx
  src/components/Layout/__tests__/SuccessAlertLayout.test.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/Table/TableSearchBar.tsx
  src/locale/it.json
  src/model/RolePermission.ts
  src/model/Station.tsx
  src/model/StationMaintenance.ts
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/stationMaintenances/addEditDetail/StationMaintenanceAddEditDetail.tsx
  src/pages/stationMaintenances/addEditDetail/__tests__/StationMaintenanceAddEditDetail.test.tsx
  src/pages/stationMaintenances/list/StationMaintenancesHoursSummary.tsx
  src/pages/stationMaintenances/list/StationMaintenancesPage.tsx
  src/pages/stationMaintenances/list/StationMaintenancesTable.tsx
  src/pages/stationMaintenances/list/StationMaintenancesTableColumns.tsx
  src/pages/stationMaintenances/list/__tests__/StationMaintenancesHoursSummary.test.tsx
  src/pages/stationMaintenances/list/__tests__/StationMaintenancesPage.test.tsx
  src/pages/stationMaintenances/list/__tests__/StationMaintenancesTable.test.tsx
  src/pages/stationMaintenances/list/__tests__/StationMaintenancesTableColumns.test.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/pages/stations/stationECList/StationECPage.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/pages/stations/stationECList/__tests__/StationECTable.test.tsx
  src/pages/stations/stationECList/__tests__/StationECTableColumns.test.tsx
  src/pages/tosAndPrivacy/TosAndPrivacy.tsx
  src/pages/tosAndPrivacy/__tests__/TosAndPrivacy.test.tsx
  src/redux/hooks.ts
  src/redux/slices/stationCISlice.ts
  src/redux/slices/stationMaintenancesSlice.ts
  src/redux/store.ts
  src/routes.tsx
  src/services/__mocks__/creditorInstitutionService.ts
  src/services/__mocks__/stationMaintenancesService.ts
  src/services/__mocks__/stationService.ts
  src/services/__tests__/stationMaintenancesService.test.ts
  src/services/__tests__/stationService.test.ts
  src/services/stationMaintenancesService.ts
  src/services/stationService.ts
  src/utils/common-utils.ts
  src/utils/constants.ts
Labels: size/large, minor

#636 fix: Pre release station maintenances
  src/pages/stationMaintenances/list/StationMaintenancesPage.tsx
Labels: size/small, patch

#637 hotfix: Fix bundle row selector e2e playwright
  e2e/package.json
  e2e/tests/utils/bundleUtils.ts
  e2e/tests/utils/e2eUtils.ts
  e2e/yarn.lock
Labels: size/small, skip

#639 fix: hasPoste flag management of related data
  src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
Labels: bug, size/small, patch

#645 [PPANTT-93] feat: Add api key ACA
  package.json
  src/locale/it.json
  src/model/ApiKey.tsx
  src/model/__tests__/ApiKey.test.tsx
Labels: size/small, minor

#643 [PPANTT-9] feat: e2e delegations' page
  .github/workflows/ci_integration_test.yml
  e2e/tests/delegations.spec.ts
Labels: size/small, skip

#644 [PPANTT-26] feat: Bundle's channel list server-side autocomplete
  src/api/BackofficeClient.ts
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
Labels: bug, size/large, patch

#646 New Release 1.30.4
  .github/workflows/ci_integration_test.yml
  e2e/tests/delegations.spec.ts
  package.json
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/ApiKey.tsx
  src/model/__tests__/ApiKey.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
Labels: size/large, minor

#649 [PPANTT-99] feat: New filters PSP bundles' list
  .github/workflows/ci_code_review.yml
  e2e/tests/globalBundles.spec.ts
  e2e/tests/privateBundles.spec.ts
  e2e/tests/publicBundles.spec.ts
  e2e/tests/utils/bundleUtils.ts
  openApi/scripts/api-portal_fixPostGen.js
  package.json
  src/api/BackofficeClient.ts
  src/components/Form/GenericModal.tsx
  src/locale/it.json
  src/model/__tests__/ApiKey.test.tsx
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/__tests__/CommissionBundlesPage.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesSearchBar.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesSearchBar.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTable.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
  src/services/__tests__/bundleService.test.ts
  src/services/__tests__/taxonomyService.test.ts
  src/services/bundleService.ts
  src/services/taxonomyService.ts
  src/utils/common-utils.ts
Labels: size/large, minor
