Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-07, with the labels that each got.

#593 Hotfix Bundle Banco Sardegna
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/services/__mocks__/institutionsService.ts
Labels: size/small, patch

#586 [VAS-1070] feat; Change station and channel detail view on pending update
  package.json
  src/api/BackofficeClient.ts
  src/components/WrapperCommon/GetAlert.tsx
  src/components/WrapperCommon/StatusChip.tsx
  src/components/WrapperCommon/__tests__/GetAlert.test.tsx
  src/locale/it.json
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/AddEditChannelPage.tsx
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/channels/detail/__tests__/ChannelDetailHeader.test.tsx
  src/pages/channels/detail/__tests__/DetailButton.test.tsx
  src/pages/channels/detail/__tests__/GetChannelAlert.test.tsx
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/detail/components/DetailButtons.tsx
  src/pages/channels/detail/components/GetChannelAlert.tsx
  src/pages/channels/detail/components/__tests__/ChannelDetails.test.tsx
  src/pages/channels/detail/components/__tests__/DetailButtons.test.tsx
  src/pages/channels/list/ChannelsTable.tsx
  src/pages/channels/list/ChannelsTableColumns.tsx
  src/pages/delegations/detail/DelegationStationDetailsDrawer.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/addEditStation/AddEditStationPage.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/detail/components/DetailButtonsStation.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/pages/stations/list/StationsTableColumns.tsx
  src/pages/stations/list/__tests__/StationsTableColumns.test.tsx
  src/routes.tsx
  src/services/__tests__/channelService.test.ts
  src/services/__tests__/stationService.test.ts
  src/services/channelService.ts
  src/services/stationService.ts
Labels: enhancement, size/large, minor

#595 fix: psp bundle list and idBrokerPsp
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/services/__mocks__/bundleService.ts
  src/utils/channel-utils.ts
Labels: size/small, patch

#596 fix: Missing translate
  src/locale/it.json
Labels: bug, size/small, patch

#597 fix: Bugs found before release
  src/model/Channel.tsx
  src/model/CommissionBundle.ts
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
Labels: size/large, patch

#605 [VAS-1146] feat: Implement new boolean "cart" for bundles
  package.json
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailConfiguration.test.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/institutionsService.ts
Labels: size/large, minor

#611 Next Release 1.28.0
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailConfiguration.test.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/institutionsService.ts
Labels: size/large, minor

#612 hotfix: Integration test action
  .github/workflows/ci_integration_test.yml
  .gitignore
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/download_pem.sh
Labels: size/small, patch, hotfix

#607 [VAS-1166] feat: add tos and privacy pages
  src/App.tsx
  src/__tests__/App.test.tsx
  src/components/CommonFooter/CommonFooter.tsx
  src/components/Layout/Layout.tsx
  src/components/Snippet/Snippet.tsx
  src/components/Snippet/__tests__/Snippet.test.tsx
  src/components/TOS/TOSWall.tsx
  src/data/privacy.json
  src/data/tos.json
  src/locale/it.json
  src/pages/tos/TOS.tsx
  src/pages/tos_and_privacy/TOS_AND_PRIVACY.tsx
  src/pages/tos_and_privacy/__tests__/TOS_AND_PRIVACY.test.tsx
  src/routes.tsx
  src/utils/dom-utility.ts
  src/utils/onetrust-utils.ts
Labels: enhancement, size/large, minor

#613 Next
  package.json
  src/App.tsx
  src/__tests__/App.test.tsx
  src/components/CommonFooter/CommonFooter.tsx
  src/components/Layout/Layout.tsx
  src/components/Snippet/Snippet.tsx
  src/components/Snippet/__tests__/Snippet.test.tsx
  src/components/TOS/TOSWall.tsx
  src/data/privacy.json
  src/data/tos.json
  src/locale/it.json
  src/pages/tos/TOS.tsx
  src/pages/tos_and_privacy/TOS_AND_PRIVACY.tsx
  src/pages/tos_and_privacy/__tests__/TOS_AND_PRIVACY.test.tsx
  src/routes.tsx
  src/utils/dom-utility.ts
  src/utils/onetrust-utils.ts
  yarn.lock
Labels: size/large, minor

#620 [VAS-1203] hotfix bundle date from
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
Labels: size/small, patch

#619 fix: error boundary label
  src/locale/it.json
Labels: size/small, patch

#622 hotfix: ErrorBoundary labels
  src/locale/it.json
Labels: bug, size/small, patch, hotfix

#606 [VAS-785] feat: Introduce new flags "standIn" & "aca" for CI-station relation
  package.json
  src/api/BackofficeClient.ts
  src/components/Form/ECSelection.tsx
  src/locale/it.json
  src/model/Station.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/pages/stations/stationECList/StationECPage.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/pages/stations/stationECList/__tests__/StationECTable.test.tsx
  src/pages/stations/stationECList/__tests__/StationECTableColumns.test.tsx
  src/redux/slices/stationCISlice.ts
  src/redux/store.ts
  src/routes.tsx
  src/services/__mocks__/creditorInstitutionService.ts
  src/services/__mocks__/stationService.ts
  src/services/__tests__/stationService.test.ts
  src/services/stationService.ts
Labels: bug, enhancement, size/large, minor
