Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-04, with the labels that each got.

#427 fix currency format global bundle
  jest.config.js
  src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
  src/services/__mocks__/bundleService.ts
  src/utils/common-utils.ts
  src/utils/constants.ts
Labels: bug, size/large

#421 [VAS-894] chore: Refactor components
  src/components/SideMenu/SideMenuLayout.tsx
  src/components/SideMenu/__tests__/SideMenuLayout.test.tsx
  src/components/Table/TableUtils.tsx
  src/components/Table/__tests__/TableUtils.test.tsx
  src/locale/it.json
  src/pages/apiKeys/ApiKeysPage.tsx
  src/pages/channels/channelPSPList/ChannelPSPListPage.tsx
  src/pages/channels/channelPSPList/ChannelPSPTableColumns.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableColumns.test.tsx
  src/pages/channels/list/ChannelsPage.tsx
  src/pages/channels/list/ChannelsTableColumns.tsx
  src/pages/channels/list/__tests__/ChannelsTableColumns.test.tsx
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundlePage.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundleTaxonomies.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/BundleTaxonomiesCheckboxButton.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/BundleTaxonomiesDrawer.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/BundleTaxonomiesGroupButton.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/BundleTaxonomiesTable.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailConfiguration.test.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailTaxonomies.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesSearchBar.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesEmpty.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesSearchBar.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTable.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
  src/pages/dashboard/DashboardPage.tsx
  src/pages/dashboard/__tests__/DashboardPage.test.tsx
  src/pages/dashboard/__tests__/DashboardPage.test.tsx.old
  src/pages/dashboard/components/ECRegistrationData.tsx
  src/pages/dashboard/components/OperationTable.tsx
  src/pages/dashboard/components/PSPRegistrationData.tsx
  src/pages/dashboard/components/PTRegistrationData.tsx
  src/pages/delegations/DelegationsPage.tsx
  src/pages/delegations/__tests__/DelegationsPage.test.tsx
  src/pages/delegations/list/DelegationsTableColumns.tsx
  src/pages/delegations/list/__tests__/DelegationsTable.test.tsx
  src/pages/delegations/list/__tests__/DelegationsTableColumns.test.tsx
  src/pages/delegations/list/__tests__/DelegationsTableEmpty.test.tsx
  src/pages/delegations/list/__tests__/DelegationsTableSearchBar.test.tsx
  src/pages/iban/IbanPage.tsx
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/list/IbanTableColumns.tsx
  src/pages/iban/list/__tests__/IbanTableColumns.test.tsx
  src/pages/operationTable/list/OperationTableColumns.tsx
  src/pages/operationTable/list/OperationTableListPage.tsx
  src/pages/stations/__tests__/StationTableColumns.test.tsx
  src/pages/stations/list/StationsPage.tsx
  src/pages/stations/list/StationsTableColumns.tsx
  src/pages/stations/list/__tests__/StationsTableColumns.test.tsx
  src/pages/stations/stationECList/StationECPage.tsx
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/pages/stations/stationECList/__tests__/StationECTableColumns.test.tsx
Labels: enhancement, size/large

#422 [VAS-900] integration test Global Bundle
  .env.development.local
  .github/workflows/integration_test.yml
  .gitignore
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/terraform.tfvars
  integration-test/01_iban_add.js
  integration-test/01_iban_delete.js
  integration-test/features/README.md
  integration-test/features/apikey.feature
  integration-test/features/iban.feature
  integration-test/features/psp_bundle.feature
  integration-test/features/stations.feature
  integration-test/features/step_definitions/alias.json
  integration-test/features/step_definitions/create_jwt.js
  integration-test/features/step_definitions/login.js
  integration-test/features/step_definitions/steps.js
  integration-test/features/step_definitions/user_event.js
  integration-test/package.json
  integration-test/yarn.lock
  package.json
  src/components/CommonHeader/CommonHeader.tsx
  src/hooks/useLogin.ts
  src/hooks/useSelectedParty.tsx
  src/pages/channels/channelPSPList/__tests__/ChannelPSPTableColumns.test.js
  src/pages/channels/list/__tests__/ChannelsTableColumns.test.js
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/list/CommissionBundlesSearchBar.tsx
  src/pages/delegations/__tests__/DelegationsPage.test.js
  src/pages/stations/list/__tests__/StationsTableColumns.test.js
  src/pages/stations/stationECList/__tests__/StationECTableColumns.test.js
  src/services/institutionService.ts
  yarn.lock
Labels: size/large

#430 [VAS-775][VAS-890] feat: minor changes
  .env.development.local
  src/locale/it.json
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/tos/TOS.tsx
Labels: enhancement, size/small, patch

#429 [VAS-864] feat: add user and groups to bo nav
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx.old
  src/locale/it.json
Labels: enhancement, size/large, patch

#433 [VAS-887] fix: Fixed APIs' error handling
  src/locale/it.json
  src/pages/apiKeys/AddApiKeyPage.tsx
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/AddEditChannelPage.tsx
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
  src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
  src/pages/paymentsReceipts/list/__tests__/PaymentsreceiptsTable.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/utils/client-utils.ts
Labels: bug, enhancement, size/large

#432 [VAS-687] feat: Add delegation detail page
  package.json
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/Table/TableEmptyState.tsx
  src/components/Table/TableSearchBar.tsx
  src/locale/it.json
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/delegations/detail/DelegationDetailOperativeTable.tsx
  src/pages/delegations/detail/DelegationDetailPage.tsx
  src/pages/delegations/detail/DelegationDetailPaymentContacts.tsx
  src/pages/delegations/detail/DelegationStationDetailsDrawer.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailOperativeTable.test.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailPage.test.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailPaymentContacts.test.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailStationDetailsDrawer.test.tsx
  src/pages/delegations/detail/list/DelegationStationsTable.tsx
  src/pages/delegations/detail/list/DelegationStationsTableColumns.tsx
  src/pages/delegations/detail/list/__tests__/DelegationStationsTable.test.tsx
  src/pages/delegations/detail/list/__tests__/DelegationStationsTableColumns.test.tsx
  src/pages/delegations/list/DelegationsTable.tsx
  src/pages/delegations/list/DelegationsTableColumns.tsx
  src/pages/delegations/list/__tests__/DelegationsTable.test.tsx
  src/pages/delegations/list/__tests__/DelegationsTableColumns.test.tsx
  src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
  src/redux/slices/delegationDetailSlice.ts
  src/redux/store.ts
  src/routes.tsx
  src/services/__mocks__/brokerService.ts
  src/services/__mocks__/creditorInsitutionService.ts
  src/services/__tests__/brokerService.test.ts
  src/services/__tests__/creditorInstitutionService.test.ts
  src/services/brokerService.ts
  src/services/creditorInstitutionService.ts
  src/utils/constants.ts
Labels: enhancement, size/large

#435 [VAS-876] fix: Firefox graphic bug
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesCheckboxButton.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesGroupButton.tsx
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
  src/services/__mocks__/ibanService.ts
Labels: bug, size/large

#436 [VAS-928] fix: Changed idBrokerPsp from institution_name to broker_id
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/institutionsService.ts
  src/utils/channel-utils.ts
Labels: bug, size/small

#437 fix: modal ecName
  src/pages/stations/stationECList/StationECTable.tsx
Labels: size/small

#438 fix: Hide pagination CUP
  src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
Labels: bug, size/small

#439 [VAS-844] feat: Enable direct/undirect connection flag
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/Node.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPage.test.tsx
  src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
  src/pages/delegations/detail/DelegationDetailPage.tsx
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/stationService.ts
  src/services/__tests__/brokerService.test.ts
  src/services/__tests__/pspBrokerService.test.ts
  src/services/brokerService.ts
  src/services/pspBrokerService.ts
Labels: size/large

#441 [VAS-929] fix: Logic on go to delegation detail button
  src/pages/delegations/list/DelegationsTableColumns.tsx
  src/services/__mocks__/brokerService.ts
Labels: size/small

#442 [VAS-950] fix: Commission bundles' bug empty taxonomies
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundlePage.test.tsx
  src/utils/__tests__/common-utils.test.ts
  src/utils/common-utils.ts
Labels: size/large

#443 fix: CUP Payments Receipts filter date & format date
  src/api/BackofficeClient.ts
  src/pages/paymentsReceipts/list/PaymentsReceiptsTableColumns.tsx
  src/pages/paymentsReceipts/list/__tests__/PaymentsreceiptsTable.test.tsx
Labels: size/small

#444 [VAS-914] feat: Implement debtorOrIuv CUP filter and pagination
  src/api/BackofficeClient.ts
  src/components/Table/TableSearchBar.tsx
  src/components/Table/__tests__/TableSearchBar.test.tsx
  src/locale/it.json
  src/model/PaymentsReceipts.ts
  src/pages/paymentsReceipts/PaymentsReceiptsPage.tsx
  src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
  src/services/__mocks__/paymentsReceiptsService.ts
  src/services/paymentsReceiptsService.ts
Labels: enhancement, size/small

#445 [VAS-952] Improve for PROD release
  src/locale/it.json
  src/pages/dashboard/DashboardPage.tsx
  src/pages/dashboard/components/NextSteps.tsx
  src/pages/delegations/DelegationsPage.tsx
  src/pages/delegations/__tests__/DelegationsPage.test.js
  src/pages/delegations/__tests__/DelegationsPage.test.tsx
  src/utils/constants.ts
Labels: size/small

#446 [VAS-772] feat: add station testing
  package.json
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/pages/stations/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/__tests__/AddEditStationForm.test.tsx.old
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/services/__mocks__/stationService.ts
  src/services/__tests__/stationService.test.ts
  src/services/__tests__/stationService.test.ts.old
  src/services/stationService.ts
  src/utils/env.ts
Labels: size/large, minor

#448 fix: Change PT broker type disabled check from total_items to items_found
  src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
Labels: bug, size/small

#449 Vas 913 operation pago pa deve poter loggarsi in tutti gli enti di self care
  .pre-commit-config.yaml
  src/api/BackofficeClient.ts
  src/components/CommonHeader/CommonHeader.tsx
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/CommonHeader/__tests__/CommonHeader.test.tsx
  src/components/__tests__/Header.test.tsx
  src/pages/stations/addEditStation/AddEditStationPage.tsx
  src/services/creditorInstitutionService.ts
  src/services/institutionService.ts
  src/services/partyService.ts
  src/utils/rbac-utils.ts
Labels: enhancement, size/large

#450 [VAS-964] feat: reworked station testing to include different types
  src/api/BackofficeClient.ts
  src/pages/stations/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/services/__tests__/stationService.test.ts
  src/services/stationService.ts
Labels: enhancement, size/small, minor

#454 operator pagopa
  src/model/RolePermission.ts
Labels: size/small

#453 fix: cert test failure label on station testing
  src/pages/stations/addEditStation/AddEditStationForm.tsx
Labels: bug, size/small

#447 [VAS-738] feat: Bundle's subscription requests table for PUBLIC bundles
  src/api/BackofficeClient.ts
  src/components/PaddedDrawer.tsx
  src/components/Table/TableEmptyState.tsx
  src/components/Table/TableSearchBar.tsx
  src/components/Table/TableUtils.tsx
  src/components/Table/__tests__/TableSearchBar.test.tsx
  src/locale/it.json
  src/model/CommissionBundle.ts
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleTaxonomies.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/BundleTaxonomiesTable.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/__tests__/BundleTaxonomiesCheckboxButton.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/__tests__/BundleTaxonomiesDrawer.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/__tests__/BundleTaxonomiesGroupButton.test.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailConfiguration.test.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailTaxonomies.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsColumns.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsDrawer.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsTable.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsColumns.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsDrawer.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsTable.test.tsx
  src/pages/delegations/DelegationsPage.tsx
  src/pages/delegations/detail/DelegationDetailPage.tsx
  src/pages/delegations/detail/DelegationStationDetailsDrawer.tsx
  src/pages/paymentsReceipts/PaymentsReceiptsPage.tsx
  src/pages/paymentsReceipts/__tests__/PaymentsReceiptsPage.test.tsx
  src/pages/paymentsReceipts/list/__tests__/PaymentsreceiptsTable.test.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
  src/utils/constants.ts
Labels: enhancement, size/large

#452 [VAS-915][VAS-917] fix: Create/edit bundle imports validation & validity date bug
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundlePage.test.tsx
  src/utils/common-utils.ts
Labels: bug, size/large
