Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-09, with the labels that each got.

#650 fix: SideMenu station maintenances link for PT users
  src/components/SideMenu/SideMenu.tsx
Labels: size/small, patch

#654 fix: Remove currency icon and re-align bundle table columns
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
Labels: size/small, patch

#655 fix: Center bundle's table payment columns
  src/components/Table/TableUtils.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
Labels: size/small, patch

#661 hotfix: Channels & Stations endpoint visualization & Channel's pagination
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/list/ChannelsTable.tsx
  src/pages/stations/detail/components/StationDetails.tsx
Labels: size/small, patch

#663 fix: Private bundles e2e
  e2e/tests/privateBundles.spec.ts
Labels: size/small, skip

#665 hotfix: Pagination bundle's subscription table pt2
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
Labels: size/small, patch

#666 fix: Currency format from string to number cent - float conversion bug
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/utils/common-utils.ts
Labels: size/small, patch

#667 [PPANTT-130] feat: Re-enable "PO" payment type
  .github/workflows/check_pr.yml
  src/utils/constants.ts
Labels: size/small, patch

#662 [PPANTT-72] feat: Station REST services configuration
  src/locale/it.json
  src/model/Channel.tsx
  src/model/Station.tsx
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/services/__mocks__/stationService.ts
  src/utils/station-utils.ts
Labels: size/large, minor

#673 [PPANTT-129] feat: Update associate and dissociate CI-Station relation
  package.json
  src/api/BackofficeClient.ts
  src/components/Table/TableDataGrid.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/components/ConfirmModal.tsx
  src/pages/delegations/detail/list/DelegationStationsTable.tsx
  src/pages/stationMaintenances/list/__tests__/StationMaintenancesTable.test.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/pages/stations/stationECList/__tests__/StationECTable.test.tsx
  src/pages/stations/stationECList/__tests__/StationECTableColumns.test.tsx
  src/services/stationService.ts
  src/utils/constants.ts
Labels: minor

#680 [PPANTT-140] fix: Add role EC_ADMIN to payment notices permissions
  .github/workflows/check_pr.yml
  .github/workflows/github_scripts/check_source_branch.js
  src/model/RolePermission.ts
Labels: size/small, patch
