Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-06, with the labels that each got.

#528 Upgrade openapi client generation
  .github/workflows/ci_code_review.yml
  openApi/scripts/api-portal_fixPreGen.js
  package.json
  src/api/BackofficeClient.ts
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/Form/ECSelection.tsx
  src/components/Form/__tests__/ECSelection.test.tsx
  src/pages/apiKeys/AddApiKeyPage.tsx
  src/pages/apiKeys/ApiKeysCard.tsx
  src/pages/apiKeys/ApiKeysPage.tsx
  src/pages/apiKeys/__tests__/AddApiKeyPage.test.tsx
  src/pages/apiKeys/__tests__/ApiKeysCard.test.tsx
  src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
  src/pages/channels/channelAssociatePSP/__tests__/PSPSelectionSearch.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/services/__mocks__/apiKeyService.ts
  src/services/__mocks__/creditorInstitutionService.ts
  src/services/__mocks__/institutionsService.ts
  src/services/__mocks__/partyService.ts
  src/services/__tests__/apiKeyService.test.ts
  src/services/__tests__/institutionService.test.ts
  src/services/__tests__/partyService.test.ts
  src/services/__tests__/partyService.test.ts.old
  src/services/__tests__/productService.test.ts
  src/services/__tests__/productService.test.ts.old
  src/services/apiKeyService.ts
  src/services/creditorInstitutionService.ts
  src/services/institutionService.ts
  src/services/partyService.ts
  src/services/productService.ts
  src/utils/__tests__/rbac-utils.test.ts
  src/utils/rbac-utils.ts
  yarn.lock
Labels: enhancement, size/large, minor

#536 fix: CI station association form message
  package.json
  src/locale/it.json
Labels: size/small, patch

#537 fix: Comment csv dropzone for taxonomies in create bundle page
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleTaxonomies.test.tsx
Labels: bug, patch

#538 fix: GHA deploy dev
  .github/workflows/cd_next.yml
Labels: bug, size/small, skip

#541 Fix operator multiple psp
  .github/workflows/ci_code_review.yml
  package.json
  src/components/CommonHeader/MyHeaderProduct.tsx
Labels: size/small, patch

#535 [VAS-807] feat: Implement Private Bundle add recipients page for PSP
  package.json
  public/file/recipientsExample.csv
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/Form/ECSelection.tsx
  src/components/Form/__tests__/ECSelection.test.tsx
  src/locale/it.json
  src/model/RolePermission.ts
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailOffersAddRecipientsPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailOffersAddRecipientsPage.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
  src/pages/delegations/detail/DelegationDetailPage.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/redux/hooks.ts
  src/routes.tsx
  src/services/__mocks__/creditorInstitutionService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
  src/services/creditorInstitutionService.ts
  src/utils/constants.ts
Labels: size/large, minor

#552 [VAS-1108] feat: Update delete offer API
  package.json
  src/api/BackofficeClient.ts
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
  src/services/bundleService.ts
Labels: enhancement, minor

#551 [VAS-1069] feat: Implement APIs accept/reject offers
  package.json
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailActivationPage.test.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleDetailSubscriptionsTable.test.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
Labels: size/large, minor

#553 [VAS-1114] feat: Refactor private bundles state filter
  package.json
  src/components/Table/TableDataGrid.tsx
  src/components/Table/TableEmptyState.tsx
  src/locale/it.json
  src/model/CommissionBundle.ts
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleDetailSubscriptionsTable.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTable.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
Labels: size/large, minor

#557 hotfix : Set ABI with BIC code on bundle creation for foreign PSP
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
Labels: size/large, patch, hotfix

#550 [VAS-1115] fix: Change dynamically the StationDetails page subtitle based on station wrapper status
  src/locale/it.json
  src/pages/stations/detail/components/StationDetails.tsx
Labels: bug, size/large, patch, hotfix

#555 [VAS-1117] fix: Team's testing found bugs
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
Labels: size/small, patch

#559 hotfix: ABI logic
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
Labels: size/small, patch, hotfix

#554 [VAS-1094] feat: e2e PSP create/edit/delete global bundle
  .eslintrc.js
  .github/workflows/ci_code_review.yml
  .github/workflows/ci_integration_test.yml
  .gitignore
  e2e/.gitignore
  e2e/bundleUtils.js
  e2e/e2eUtils.ts
  e2e/package.json
  e2e/playwright.config.ts
  e2e/tests/globalBundles.spec.ts
  e2e/tsconfig.e2e.json
  e2e/yarn.lock
  sonar-project.properties
  tsconfig.json
  yarn.lock
Labels: size/large, skip

#543 fix: notice ci page
  src/components/SideMenu/SideMenu.tsx
  src/pages/notices/PaymentNoticesPage.tsx
  src/pages/notices/__tests__/PaymentNoticesPage.test.tsx
  src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
  src/pages/notices/addEdit/PaymentNoticesAddEditPage.tsx
  src/pages/notices/addEdit/__tests__/PaymentNoticesAddEditForm.test.tsx
  src/pages/notices/addEdit/__tests__/PaymentNoticesAddEditPage.test.tsx
  src/pages/notices/detail/__tests__/PaymentNoticesDetailPage.test.tsx
  src/redux/slices/institutionsDataDetailsSlice.ts
Labels: size/small, patch

#560 Fix gha
  .github/workflows/ci_integration_test.yml
  .github/workflows/deploy_on_cdn.yml
Labels: size/small

#556 [VAS-1108] feat: Update delete bundle api
  package.json
  src/api/BackofficeClient.ts
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
Labels: enhancement, size/small, minor

#569 hotfix bic signin
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
Labels: size/small, patch

#575 exclude N/A as a valid ABI code
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
Labels: size/small, patch

#579 [VAS-418] feat: Align TOS page with UI design
  src/components/TOS/TOSWall.tsx
  src/locale/it.json
Labels: size/small, patch

#577 fix: notices ci detail
  src/pages/notices/detail/PaymentNoticesDetailPage.tsx
Labels: size/small, patch

#581 hotfix: Stations in status TO_FIX_UPDATE
  src/pages/stations/addEditStation/AddEditStationForm.tsx
Labels: size/large, patch, hotfix

#573 feat: Review channel flow
  .github/workflows/ci_code_review.yml
  package.json
  src/api/BackofficeClient.ts
  src/components/StatusChip.tsx
  src/locale/it.json
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/AddEditChannelPage.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelPage.test.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/channels/detail/__tests__/ChannelDetails.test.tsx
  src/pages/channels/detail/__tests__/ChannelDetailsWrap.test.tsx
  src/pages/channels/detail/__tests__/DetailButton.test.tsx
  src/pages/channels/detail/__tests__/GetChannelAlert.test.tsx
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/detail/components/ChannelDetailsWrap.tsx
  src/pages/channels/detail/components/DetailButtons.tsx
  src/pages/channels/detail/components/GetChannelAlert.tsx
  src/pages/channels/list/ChannelsPage.tsx
  src/pages/channels/list/ChannelsTable.tsx
  src/pages/channels/list/ChannelsTableColumns.tsx
  src/pages/channels/list/ChannelsTableSearchBar.tsx
  src/pages/channels/list/__tests__/ChannelsPage.test.tsx
  src/pages/channels/list/__tests__/ChannelsTable.test.tsx
  src/pages/channels/list/__tests__/ChannelsTableSearchBar.test.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/pages/stations/list/StationsTable.tsx
  src/pages/stations/list/StationsTableColumns.tsx
  src/pages/stations/list/StationsTableSearchBar.tsx
  src/pages/stations/list/__tests__/StationsTable.test.tsx
  src/pages/stations/list/__tests__/StationsTableColumns.test.tsx
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/stationService.ts
  src/services/__tests__/channelService.test.ts
  src/services/channelService.ts
Labels: enhancement, size/large, minor

#574 [VAS-1123] feat: Remove unused Station and Channel API
  package.json
  src/api/BackofficeClient.ts
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/channels/detail/__tests__/ChannelDetailHeader.test.tsx
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/detail/components/DetailButtons.tsx
  src/pages/channels/list/__tests__/ChannelsTable.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
  src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInECForm.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
  src/pages/stations/list/__tests__/StationsTable.test.tsx
  src/services/__mocks__/stationService.ts
  src/services/__tests__/channelService.test.ts
  src/services/__tests__/stationService.test.ts
  src/services/channelService.ts
  src/services/stationService.ts
Labels: enhancement, size/large, minor

#580 [VAS-1104] feat: New bundle status for available but expired bundles
  package.json
  src/locale/it.json
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
Labels: size/large, minor

#583 [VAS-1103] feat: Add new field pspBusinessName to bundle details
  package.json
  src/locale/it.json
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailConfiguration.test.tsx
Labels: size/small, minor

#585 chore: Merge main into next
  .github/workflows/ci_code_review.yml
  README.md
  package.json
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  yarn.lock
Labels: size/large, patch

#584 [VAS-1133] feat: Add new api key for printPaymentsNotice product
  src/locale/it.json
  src/model/ApiKey.tsx
  src/model/__tests__/ApiKey.test.tsx
  src/pages/apiKeys/AddApiKeyPage.tsx
  src/pages/apiKeys/__tests__/AddApiKeyPage.test.tsx
Labels: size/large, minor
