Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2024-05, with the labels that each got.

#463 routes fixed
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/components/ProtectedRoute/__tests__/ProtectedRoute.test.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/SidenavItem.tsx
  src/utils/constants.ts
Labels: bug, enhancement, size/small

#464 [VAS-777] feat: Public bundles table for Creditor institutions
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
Labels: enhancement, size/large

#466 Removed Old Flags
  .env
  .env.development.local
  .env.test.local
  .github/workflows/release_deploy.yml
  package.json
  src/App.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/pages/dashboard/DashboardPage.tsx
  src/services/nodeService.ts
  src/services/partyService.ts
  src/utils/env.ts
Labels: size/small, skip

#472 [VAS-1005] chore: Updated client
  src/api/BackofficeClient.ts
Labels: size/small

#473 new style for MyHeaderProduct
  .github/workflows/release_deploy.yml
  package.json
  src/components/CommonHeader/MyHeaderProduct.tsx
Labels: enhancement, size/small

#465 [VAS-778] feat: Ci Public bundles' details action buttons
  src/api/BackofficeClient.ts
  src/components/CommonHeader/CommonHeader.tsx
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/CommonHeader/__tests__/CommonHeader.test.tsx
  src/components/Header.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/components/__tests__/Header.test.tsx
  src/hooks/useUserRole.ts
  src/locale/it.json
  src/model/CommissionBundle.ts
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/AddEditChannelPage.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/pages/channels/detail/ChannelDetailPage.tsx
  src/pages/channels/detail/components/ChannelDetails.tsx
  src/pages/channels/detail/components/DetailButtons.tsx
  src/pages/channels/list/ChannelsTableSearchBar.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsTable.tsx
  src/pages/components/ConfirmModal.tsx
  src/pages/dashboard/__tests__/NextSteps.test.tsx
  src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
  src/pages/delegations/detail/DelegationDetailPage.tsx
  src/pages/stations/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/__tests__/StationDetailPage.test.tsx
  src/pages/stations/__tests__/StationDetails.test.tsx
  src/pages/stations/__tests__/StationDetailsValidation.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/detail/components/DetailButtonsStation.tsx
  src/pages/stations/detail/components/StationDetailsValidation.tsx
  src/pages/stations/list/StationsTableSearchBar.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
Labels: enhancement, size/large

#474 [VAS-955] feat: Updated accept and reject public subscription API
  src/api/BackofficeClient.ts
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsTable.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsTable.test.tsx
  src/services/bundleService.ts
Labels: size/small

#475 [VAS-958] feat: Creditor insitution bundle activation page
  src/App.tsx
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/RolePermission.ts
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailActivationPage.test.tsx
  src/routes.tsx
  src/services/__mocks__/bundleService.ts
  src/services/bundleService.ts
  src/utils/common-utils.ts
  src/utils/constants.ts
Labels: enhancement, size/large

#476 fix: Button to create bundle in table empty state was rendering for Creditor Institutions
  src/components/Table/TableEmptyState.tsx
  src/locale/it.json
  src/pages/commisionalBundles/list/CommissionBundlesEmpty.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesEmpty.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTable.test.tsx
Labels: bug, size/large

#477 [VAS-1006] feat: Eable payment contacts section
  src/pages/delegations/detail/DelegationDetailPage.tsx
Labels: size/small

#478 [VAS-996] fix: Bug duplicated taxonomies
  src/api/BackofficeClient.ts
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesCheckboxButton.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesGroupButton.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/__tests__/BundleTaxonomiesDrawer.test.tsx
  src/services/__mocks__/taxonomyService.ts
  src/services/__tests__/configurationService.test.ts
  src/services/configurationService.ts
Labels: bug, size/small

#479 prerelease
  .github/release.yml
  .github/workflows/check_pr.yml
  .github/workflows/release_deploy.yml
Labels: size/small, skip

#480 [VAS-1022] fix: Improve user experience and solve security issues
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/__tests__/CommissionBundlesPage.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundlePage.test.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsDrawer.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/delegations/detail/DelegationDetailPage.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailPage.test.tsx
  src/redux/hooks.ts
Labels: bug, enhancement

#481 [VAS-1017] feat: Add commission fee details to bundle detail page for CIs
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/model/CommissionBundle.ts
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/__tests__/CommissionBundlesPage.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundlePage.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleTaxonomies.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/BundleTaxonomiesTable.test.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailActivationPage.test.tsx
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailTaxonomies.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsDrawer.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
  src/redux/slices/bundleDetailsSlice.ts
  src/services/__mocks__/bundleService.ts
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
Labels: enhancement, size/large, minor

#488 [VAS-1033] feat: Change bundle types italian translation
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
Labels: enhancement, size/small, minor

#491 [VAS-1030] feat: Implement "all taxonomy" commission fee
  src/locale/it.json
  src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailTaxonomies.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsDrawer.tsx
  src/services/__tests__/bundleService.test.ts
  src/services/bundleService.ts
Labels: size/small, minor

#490 [VAS-1041] feat: Implement maintenance message api
  src/App.tsx
  src/__tests__/App.test.tsx
  src/__tests__/App.test.tsx.old
  src/api/BackofficeClient.ts
  src/locale/it.json
  src/pages/maintenance/MaintenancePage.tsx
  src/services/__mocks__/maintenanceService.ts
  src/services/__tests__/maintenanceService.test.ts
  src/services/maintenanceService.ts
Labels: minor

#492 PT types logic
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/hooks/useOrganizationType.ts
  src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesTable.test.tsx
  src/pages/dashboard/__tests__/NextSteps.test.tsx
  src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx
  src/pages/dashboard/components/NextSteps.tsx
  src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
  src/pages/stations/__tests__/StationDetailPage.test.tsx
Labels: size/small, patch

#493 hostfix org type and roles
  package.json
  src/hooks/useOrganizationType.ts
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
Labels: size/small, patch

#489 [VAS-951] feat: Implement connection type's radio buttons for AddEdit station page
  src/components/Table/TableEmptyState.tsx
  src/locale/it.json
  src/model/Station.tsx
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/list/ChannelTableEmpty.tsx
  src/pages/channels/list/ChannelsTable.tsx
  src/pages/channels/list/__tests__/ChannelsTable.test.tsx
  src/pages/channels/list/__tests__/ChannelsTableEmpty.test.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/stations/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/__tests__/StationTableEmpty.test.tsx
  src/pages/stations/__tests__/StationsTable.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
  src/pages/stations/detail/components/StationDetailsValidation.tsx
  src/pages/stations/list/StationTableEmpty.tsx
  src/pages/stations/list/StationsTable.tsx
  src/services/__mocks__/stationService.ts
Labels: size/large, minor

#494 fix: Change create bundle message it translation
  src/locale/it.json
Labels: size/small, patch

#495 fix: Translation for bundle edit page & taxonomy bug
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/BundleTaxonomiesTable.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/services/__mocks__/bundleService.ts
Labels: size/small, patch

#498 New inputs for GHA Release and Deploy
  .env.development.local
  .github/workflows/release_deploy.yml
Labels: size/small, skip

#496 [VAS-1009] feat: Implement station sync flag from Backend
  src/api/BackofficeClient.ts
  src/pages/stations/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/addEditStation/AddEditStationPage.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/services/__mocks__/stationService.ts
  src/services/stationService.ts
  src/utils/station-utils.ts
Labels: size/large, minor

#504 [VAS-947] feat: Pagopa Operator stations' table
  src/api/BackofficeClient.ts
  src/components/StatusChip.tsx
  src/components/Table/CustomDataGrid.tsx
  src/components/Table/TableDataGrid.tsx
  src/components/Table/TableEmptyState.tsx
  src/components/Table/TableSearchBar.tsx
  src/components/Table/__tests__/TableSearchBar.test.tsx
  src/locale/it.json
  src/model/Station.tsx
  src/pages/channels/channelPSPList/ChannelPSPTable.tsx
  src/pages/channels/list/ChannelsTable.tsx
  src/pages/commisionalBundles/CommissionBundlesPage.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsTable.tsx
  src/pages/commisionalBundles/list/CommissionBundlesSearchBar.tsx
  src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
  src/pages/commisionalBundles/list/__tests__/CommissionBundlesSearchBar.test.tsx
  src/pages/delegations/detail/list/DelegationStationsTable.tsx
  src/pages/delegations/list/DelegationsTable.tsx
  src/pages/iban/list/IbanTable.tsx
  src/pages/operationTable/list/OperationTableList.tsx
  src/pages/paymentsReceipts/PaymentsReceiptsPage.tsx
  src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
  src/pages/stations/__tests__/StationPage.test.tsx
  src/pages/stations/__tests__/StationsPage.test.tsx
  src/pages/stations/__tests__/StationsTable.test.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationFormSectionTitle.test.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationPage.test.tsx
  src/pages/stations/detail/__tests__/StationDetailPage.test.tsx
  src/pages/stations/detail/components/__tests__/StationDetails.test.tsx
  src/pages/stations/detail/components/__tests__/StationDetailsValidation.test.tsx
  src/pages/stations/list/StationsPage.tsx
  src/pages/stations/list/StationsTable.tsx
  src/pages/stations/list/StationsTableColumns.tsx
  src/pages/stations/list/__tests__/StationsTable.test.tsx
  src/pages/stations/list/__tests__/StationsTableColumns.test.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/services/__mocks__/stationService.ts
  src/services/__tests__/stationService.test.ts
  src/services/stationService.ts
Labels: size/large, minor

#508 [VAS-1051] feat: Permit bundle's commission fee to be zero
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
Labels: bug, size/small, patch

#506 [VAS-1050] Updated get segregation code API
  src/api/BackofficeClient.ts
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/services/__mocks__/stationService.ts
  src/services/__tests__/stationService.test.ts
  src/services/stationService.ts
Labels: enhancement, size/large, minor

#509 Static Web App
  .env.development.local
  .github/workflows/code_review.yml
  .github/workflows/release_deploy.yml
  public/redirect.html
Labels: size/small, skip

#514 new actions
  .github/workflows/cd_main.yml
  .github/workflows/cd_next.yml
  .github/workflows/check_pr.yml
  .github/workflows/ci_code_review.yml
  .github/workflows/ci_integration_test.yml
  .github/workflows/deploy_on_cdn.yml
  .github/workflows/github_scripts/check_required_labels.js
  .github/workflows/github_scripts/check_size.js
  .github/workflows/github_scripts/check_source_branch.js
  .github/workflows/github_scripts/make_latest_release.js
  .github/workflows/github_scripts/update_code.js
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/update_code.yml
  .github/workflows/update_gha.py
  integration-test/features/step_definitions/download_pem.sh
Labels: size/large, skip

#513 build(deps): define mui/base version
  package.json
  yarn.lock
Labels: size/large, patch

#517 fix: Generate Api portal client in code review & deploy
  .github/workflows/ci_code_review.yml
  .github/workflows/deploy_on_cdn.yml
  package.json
Labels: size/small, skip

#518 Release 1.22.0
  package.json
  yarn.lock
Labels: size/large

#519 Merge main -> next fix: Generate Api portal client in code review & deploy (#517)
  .github/workflows/ci_code_review.yml
  .github/workflows/deploy_on_cdn.yml
  package.json
Labels: size/small, skip

#507 [VAS-820] feat: Operator's station detail page & request edit modal
  .env.development.local
  src/api/BackofficeClient.ts
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/Form/GenericModal.tsx
  src/components/StatusChip.tsx
  src/locale/it.json
  src/pages/channels/list/__tests__/ChannelsTableColumns.test.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsTable.test.tsx
  src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
  src/pages/stations/addEditStation/AddEditStationForm.tsx
  src/pages/stations/addEditStation/AddEditStationPage.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationPage.test.tsx
  src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/detail/__tests__/StationDetailPage.test.tsx
  src/pages/stations/detail/components/DetailButtonsStation.tsx
  src/pages/stations/detail/components/StationDetailsValidation.tsx
  src/pages/stations/detail/components/__tests__/StationDetailsValidation.test.tsx
  src/pages/stations/list/StationsTableColumns.tsx
  src/pages/stations/list/__tests__/StationsTableColumns.test.tsx
  src/services/__mocks__/stationService.ts
  src/services/__tests__/stationService.test.ts
  src/services/stationService.ts
  src/utils/constants.ts
Labels: size/large, minor, on hold

#520 Hotfix: Disable aux digit selection
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsTable.test.tsx
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
  src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
  src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
Labels: bug, size/large, patch

#512 [VAS-821] feat: Update creditor institution's station detail page with new design
  src/pages/stations/detail/StationDetailPage.tsx
  src/pages/stations/detail/__tests__/StationDetailPage.test.tsx
  src/pages/stations/detail/components/DetailButtonsStation.tsx
  src/pages/stations/detail/components/StationDetails.tsx
  src/pages/stations/detail/components/StationDetailsValidation.tsx
  src/pages/stations/detail/components/__tests__/DetailButtonsStation.test.tsx
  src/pages/stations/detail/components/__tests__/StationDetails.test.tsx
  src/pages/stations/detail/components/__tests__/StationDetailsValidation.test.tsx
  src/pages/stations/list/StationsTable.tsx
  src/pages/stations/list/__tests__/StationsTableColumns.test.tsx
  src/services/__mocks__/stationService.ts
Labels: enhancement, size/large, minor

#515 [VAS-1047] feat: Add conflict duplicate config bundle error
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
Labels: size/small, patch

#523 [VAS-1068] fix: Iban trim empty spaces
  src/pages/iban/addEditIban/AddEditIbanForm.tsx
  src/utils/common-utils.ts
Labels: bug, size/small, patch

#524 [VAS-1059] feat: Update CI station association form
  openApi/scripts/api-portal_fixPostGen.js
  package.json
  src/api/BackofficeClient.ts
  src/components/Form/ECSelection.tsx
  src/components/Form/__tests__/ECSelection.test.tsx
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailOperativeTable.test.tsx
  src/pages/delegations/detail/__tests__/DelegationDetailPaymentContacts.test.tsx
  src/pages/delegations/list/DelegationsTable.tsx
  src/pages/stations/stationAssociateEC/ECAccountItemSelection.tsx
  src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
  src/pages/stations/stationAssociateEC/ECSelectionSearchInput.tsx
  src/pages/stations/stationAssociateEC/ECSelectionSearchItemContainer.tsx
  src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
  src/pages/stations/stationAssociateEC/__tests__/ECAccountItemSelection.test.tsx
  src/pages/stations/stationAssociateEC/__tests__/ECSelectionSearch.test.tsx.old
  src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
  src/pages/stations/stationECList/StationECTable.tsx
  src/pages/stations/stationECList/__tests__/StationECTable.test.tsx
  src/services/__mocks__/creditorInsitutionService.ts
  src/services/__mocks__/creditorInstitutionService.ts
  src/services/__mocks__/stationService.ts
  src/services/__tests__/creditorInstitutionService.test.ts
  src/services/creditorInstitutionService.ts
  src/services/stationService.ts
Labels: enhancement, size/large, minor

#522 fix: Operator station request disabled and default station tab
  src/locale/it.json
  src/pages/channels/addEditChannel/AddEditChannelForm.tsx
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/pages/stations/detail/components/DetailButtonsStation.tsx
  src/pages/stations/detail/components/__tests__/DetailButtonsStation.test.tsx
  src/pages/stations/list/StationsPage.tsx
  src/pages/stations/list/__tests__/StationsPage.test.tsx
Labels: size/small, patch

#527 fix: PSP bundle state without validity date to
  src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
Labels: bug, size/small, patch
