Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2025-02, with the labels that each got.

#772 [PIDM-103] feat: Station Maintenances e2e tests
  integration-test/tests/stationMaintenances.spec.ts
Labels: size/small, skip

#775 [PIDM-160] fix(CreateStationMaintenance): Adjust fromHours and toHours to handle GMT+2 - GMT+1 correctly
  src/locale/it.json
  src/pages/stationMaintenances/addEditDetail/StationMaintenanceAddEditDetail.tsx
  src/utils/common-utils.ts
Labels: size/small, patch

#750 [PPANTT-183] feat: Implement AWS Quicksight dashboard API
  package.json
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/Form/GenericModal.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/SidenavItem.tsx
  src/hooks/useUserRole.ts
  src/locale/it.json
  src/model/Party.tsx
  src/model/RolePermission.ts
  src/pages/quicksight/QuicksightDashboardPage.tsx
  src/pages/quicksight/__tests__/QuicksightDashboardPage.test.tsx
  src/routes.tsx
  src/services/__mocks__/partyService.ts
  src/services/__mocks__/quicksightDashboardService.ts
  src/services/__tests__/quicksightDashboardService.test.ts
  src/services/quicksightDashboardService.ts
Labels: size/large, minor

#777 Update CODEOWNERS
  CODEOWNERS
Labels: size/small, skip

#779 feat: [PIDM-218] Implemented collapsable side menu
  package.json
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/SideMenuLayout.tsx
  src/components/SideMenu/SidenavItem.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
Labels: size/large, minor

#780 feat: [PIDM-87] Improvements quicksight dashboard
  package.json
  src/api/BackofficeClient.ts
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/SideMenu/SideMenu.tsx
  src/locale/it.json
  src/model/Party.tsx
  src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
  src/pages/quicksight/QuicksightDashboardPage.tsx
  src/pages/quicksight/__tests__/QuicksightDashboardPage.test.tsx
  src/services/__mocks__/quicksightDashboardService.ts
  src/services/quicksightDashboardService.ts
Labels: size/small, patch
