Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2025-05, with the labels that each got.

#809 chore: update codeowners with touchpoint team
  CODEOWNERS
Labels: size/small, skip

#810 chore: refactor Backoffice client apis to service.api format
  package.json
  src/api/BackofficeClient.ts
  src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
  src/services/__tests__/apiKeyService.test.ts
  src/services/__tests__/brokerService.test.ts
  src/services/__tests__/channelService.test.ts
  src/services/__tests__/configurationService.test.ts
  src/services/__tests__/creditorInstitutionService.test.ts
  src/services/__tests__/institutionService.test.ts
  src/services/__tests__/maintenanceService.test.ts
  src/services/__tests__/partyService.test.ts
  src/services/__tests__/paymentsReceiptsService.test.ts
  src/services/__tests__/productService.test.ts
  src/services/__tests__/pspBrokerService.test.ts
  src/services/__tests__/stationService.test.ts
  src/services/apiKeyService.ts
  src/services/brokerService.ts
  src/services/channelService.ts
  src/services/configurationService.ts
  src/services/creditorInstitutionService.ts
  src/services/featureFlagService.ts
  src/services/ibanService.ts
  src/services/institutionService.ts
  src/services/maintenanceService.ts
  src/services/nodeService.ts
  src/services/noticesService.ts
  src/services/operationTable.ts
  src/services/partyService.ts
  src/services/paymentsReceiptsService.ts
  src/services/productService.ts
  src/services/pspBrokerService.ts
  src/services/stationService.ts
Labels: size/large, patch

#812 fix: [CHK-4138] local css import
  public/css/selfhostedfonts.css
  public/index.html
Labels: size/small, minor

#818 fix: [CHK-4138] ref local css in index.html
  public/index.html
Labels: size/small, patch

#813 fix: [CHK-4139] GitHub run shell injection
  .github/workflows/ci_code_review.yml
Labels: size/small, skip
