Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2025-03, with the labels that each got.

#786 [PIDM-271] fix: Standin and CUP IBAN save on first configuration
  src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
  src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
Labels: bug, size/large, patch

#785 Next release 1.41.0
  package.json
  src/App.tsx
  src/api/BackofficeClient.ts
  src/components/CommonHeader/MyHeaderProduct.tsx
  src/components/Form/GenericModal.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/SideMenuLayout.tsx
  src/components/SideMenu/SidenavItem.tsx
  src/components/SideMenu/__tests__/SideMenu.test.tsx
  src/hooks/useUserRole.ts
  src/locale/it.json
  src/model/Party.tsx
  src/model/RolePermission.ts
  src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
  src/pages/quicksight/QuicksightDashboardPage.tsx
  src/pages/quicksight/__tests__/QuicksightDashboardPage.test.tsx
  src/routes.tsx
  src/services/__mocks__/partyService.ts
  src/services/__mocks__/quicksightDashboardService.ts
  src/services/__tests__/quicksightDashboardService.test.ts
  src/services/quicksightDashboardService.ts
Labels: size/large, minor

#790 fix: form error message translation label ref
  src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
Labels: size/small, patch

#791 feat: [PIDM-2656] Add flag onUs to Bundle form page
  integration-test/tests/globalBundles.spec.ts
  integration-test/tests/privateBundles.spec.ts
  integration-test/tests/publicBundles.spec.ts
  package.json
  src/locale/it.json
  src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
  src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
  src/pages/commisionalBundles/detail/components/CommissionBundleDetailConfiguration.tsx
  src/pages/commisionalBundles/detail/components/__tests__/CommissionBundleDetailConfiguration.test.tsx
  src/services/__mocks__/bundleService.ts
  src/services/__mocks__/channelService.ts
  src/services/__mocks__/configurationService.ts
Labels: patch

#795 fix: [PIDM-329] playwright integration tests
  .github/workflows/ci_integration_test.yml
  integration-test/tests/channel.spec.ts
  integration-test/tests/delegations.spec.ts
  integration-test/tests/globalBundles.spec.ts
  integration-test/tests/iban.spec.ts
  integration-test/tests/privateBundles.spec.ts
  integration-test/tests/publicBundles.spec.ts
  integration-test/tests/stationMaintenances.spec.ts
  integration-test/tests/stations.spec.ts
  integration-test/tests/utils/bundleUtils.ts
  integration-test/tests/utils/channelUtils.ts
Labels: bug, size/large, patch, minor, skip

#797 [PIDM-370] fix: PSP dashboard for operator
  .github/workflows/ci_code_review.yml
  package.json
  src/api/BackofficeClient.ts
  src/pages/quicksight/QuicksightDashboardPage.tsx
  src/pages/quicksight/__tests__/QuicksightDashboardPage.test.tsx
  src/services/__tests__/quicksightDashboardService.test.ts
  src/services/quicksightDashboardService.ts
Labels: size/small, patch

#799 [PIDM-379] chore: Update Quicksight dashboard error message
  package.json
  src/locale/it.json
Labels: size/small, patch
