Repository pagopa/pagopa-selfcare-frontend, pull requests merged in 2025-06, with the labels that each got.

#820 fix: UI
  src/locale/it.json
  src/pages/delegations/detail/list/DelegationStationsTableColumns.tsx
  src/pages/stations/stationECList/StationECTableColumns.tsx
  src/pages/stations/stationECList/__tests__/StationECTableColumns.test.tsx
  src/utils/station-utils.ts
Labels: patch

#821 feat:[PIDM-551]-Ruolo-Utente
  src/hooks/useUserRole.ts
  src/pages/quicksight/QuicksightDashboardPage.tsx
Labels: size/small, minor

#823 fix: Delegation page aux digit mapping
  src/pages/delegations/detail/DelegationStationDetailsDrawer.tsx
  src/pages/delegations/detail/list/DelegationStationsTableColumns.tsx
  src/utils/common-utils.ts
  src/utils/station-utils.ts
Labels: size/small, patch

#830 fix: Typo "aggioranta"
  src/locale/it.json
Labels: size/small, patch
